### PR TITLE
Improve svn and git support

### PR DESCRIPTION
**Pull request by jcfr**
This PR updates vcspull so that it can support:
* git:
 * checkout of specific revision or git_tag with exhaustive error checking
 * specifying options `git_remote_name` and `tls_verify` as keyword args to `create_repo` 
* svn:
 * specifying `svn_username` and `svn_password` as keyword args to `create_repo` (original behavior where username/password are extracted from url is still available)
 * checking out a specific svn revision
 * specifying  `svn_trust_cert` as keyword args to `create_repo` 

Remaining:
* [ ] Mock tests for svn and git

### CODE REVIEW

**Comment by tony** [comment]
@jcfr I can try to pitch in with tests.  Have you used pytest's monkeypatch before?

Any other features/behavior you're looking for?  I'm thinking of allowing ``vcspull .`` (curdir) ``vcspull ..`` (parent dir), etc. to target a directory with ``.vcspull.yaml`` in it.

**Comment by jcfr** [comment]
> I can try to pitch in with tests. 

Thanks

> Have you used pytest's monkeypatch before?

Would appreciate if you could point me to an example.

> Any other features/behavior you're looking for?

To provide some context, I use the Python API associated with vcspull. See https://github.com/jcfr/pys4ext#pys4ext

Note: I am heading out for the weekend and will be back on the computer on Monday.

**Comment by tony** [comment]
> monkeypatch examples

I retract that, I tried using it when converting from normal mock to monkeypatch.setattr but ran into problems.  Normal ``mock`` also posed with assertions when mixing in with context managers from pytest.

https://pytest.org/latest/monkeypatch.html

I'm ok with adding https://github.com/pytest-dev/pytest-mock if monkeypatch doesn't do the trick.

> To provide some context, I use the Python API associated with vcspull. See https://github.com/jcfr/pys4ext#pys4ext

Roger 👍 

> Note: I am heading out for the weekend and will be back on the computer on Monday.

I may fork your branch and try to write tests against this. Have a good weekend!

**Comment by tony** [comment]
I'm going to merge this and create a separate issue at #39 for tests.

I've done a lot of fixes / simplifications for consistency as well as removing code that's unused.

**Comment by tony** [comment]
I've followed up with a PR at #40 which will serve as another clean up / simplification of internals.

**Comment by tony** [comment]
I have split the vcs-specific stuff into [libvcs](https://github.com/tony/libvcs).  This separates the CLI front-end (vcspull) from the what you want to do.  It should also make ongoing development of the vcs abstraction more straight-forward.

In your case pys4ext can ``pip install libvcs`` and get started without any of the requirements vcspull (click, kaptan, pyyaml).

I also turned ``create_repo`` into ``create_repo_from_pip_url`` to make it more clear its accepting a pip URL.  A lot of the ambiguities with ``run`` have been ironed out.  A ``create_repo`` for normal, non-pip style vcs URL's needs to get made.  In the interim its possible to just use the raw ``GitRepo``, ``MercurialRepo`` and ``SubversionRepo`` objects.

The test issue has been moved to https://github.com/tony/libvcs/issues/3.

**Comment by jcfr** [comment]
>  vcs-specific stuff into libvcs [...] without any of the requirements

Nice. Makes sense.

> I also turned create_repo into create_repo_from_pip_url

Makes sense. 

I tried to update `pys4ext` to use libvcs and faced few issues.
See https://github.com/jcfr/pys4ext/pull/1#issuecomment-227173586

Would appreciate your guidance to address them.

Thanks
Jc

**Pull request merged**
